/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatChatIdRouteImport } from './routes/chat.$chatId'
import { Route as ApiHealthcheckRouteImport } from './routes/api/healthcheck'
import { Route as ChatChatIdIndexRouteImport } from './routes/chat.$chatId.index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthcheckRoute = ApiHealthcheckRouteImport.update({
  id: '/api/healthcheck',
  path: '/api/healthcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatIdIndexRoute = ChatChatIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatChatIdRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/chat/$chatId': typeof ChatChatIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/chat/$chatId/': typeof ChatChatIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/chat/$chatId': typeof ChatChatIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/chat/$chatId': typeof ChatChatIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/chat/$chatId/': typeof ChatChatIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/healthcheck'
    | '/chat/$chatId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/chat/$chatId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/healthcheck' | '/api/auth/$' | '/api/trpc/$' | '/chat/$chatId'
  id:
    | '__root__'
    | '/'
    | '/api/healthcheck'
    | '/chat/$chatId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/chat/$chatId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthcheckRoute: typeof ApiHealthcheckRoute
  ChatChatIdRoute: typeof ChatChatIdRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healthcheck': {
      id: '/api/healthcheck'
      path: '/api/healthcheck'
      fullPath: '/api/healthcheck'
      preLoaderRoute: typeof ApiHealthcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$chatId/': {
      id: '/chat/$chatId/'
      path: '/'
      fullPath: '/chat/$chatId/'
      preLoaderRoute: typeof ChatChatIdIndexRouteImport
      parentRoute: typeof ChatChatIdRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatChatIdRouteChildren {
  ChatChatIdIndexRoute: typeof ChatChatIdIndexRoute
}

const ChatChatIdRouteChildren: ChatChatIdRouteChildren = {
  ChatChatIdIndexRoute: ChatChatIdIndexRoute,
}

const ChatChatIdRouteWithChildren = ChatChatIdRoute._addFileChildren(
  ChatChatIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthcheckRoute: ApiHealthcheckRoute,
  ChatChatIdRoute: ChatChatIdRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
